Repository spacemeshos/post-rs, pull requests merged in 2023-05, with the labels that each got.

#46 no rayon on verification code path
  benches/verifying.rs
  ffi/src/lib.rs
  src/verification.rs
  tests/generate_and_verify.rs
Labels: codeball:needs-careful-review

#35 Initialization on GPU/CPU with openCL
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  ffi/Cargo.toml
  ffi/src/initialization.rs
  ffi/src/lib.rs
  ffi/src/post_impl.rs
  initializer/Cargo.toml
  initializer/src/main.rs
  scrypt-ocl/Cargo.toml
  scrypt-ocl/src/lib.rs
  scrypt-ocl/src/scrypt-jane.cl
  src/initialize.rs
  src/reader.rs
  tests/generate_and_verify.rs
Labels: codeball:needs-careful-review

#49 Release v0.1.7
  Cargo.lock
  Cargo.toml
  ffi/Cargo.toml
  initializer/Cargo.toml
  scrypt-ocl/Cargo.toml
Labels: codeball:approved

#54 CI: Build profiler tool and upload artifacts
  .github/workflows/ci.yml
Labels: codeball:approved, milestone/genesis

#56 Assign concrete values to DeviceClass enum
  ffi/src/initialization.rs
Labels: codeball:needs-careful-review

#63 Fix freeing initializer in C API
  ffi/src/initialization.rs
Labels: codeball:needs-careful-review

#59 Keep scrypter instance
  scrypt-ocl/src/lib.rs
Labels: codeball:needs-careful-review

#64 Fix initializing less than GWS labels with OCL
  scrypt-ocl/src/lib.rs
Labels: codeball:needs-careful-review

#60 Upload release assets automatically
  .github/workflows/ci.yml
Labels: codeball:approved

#47 Proper logging instead of prints.
  Cargo.lock
  Cargo.toml
  ffi/Cargo.toml
  ffi/build.rs
  ffi/src/initialization.rs
  ffi/src/lib.rs
  ffi/src/log.rs
  ffi/src/post_impl.rs
  initializer/Cargo.toml
  initializer/src/main.rs
  profiler/Cargo.toml
  profiler/src/main.rs
  scrypt-ocl/Cargo.toml
  scrypt-ocl/src/lib.rs
  src/initialize.rs
  src/reader.rs
Labels: codeball:needs-careful-review

#68 Remove k3pow
  benches/pow.rs
  benches/proving.rs
  benches/verifying.rs
  ffi/src/post_impl.rs
  profiler/src/main.rs
  src/compression.rs
  src/config.rs
  src/pow.rs
  src/prove.rs
  src/verification.rs
  tests/generate_and_verify.rs
Labels: codeball:needs-careful-review

#69 Release v0.1.13
  Cargo.lock
  Cargo.toml
  ffi/Cargo.toml
  initializer/Cargo.toml
  profiler/Cargo.toml
  scrypt-ocl/Cargo.toml
Labels: codeball:approved

#75 Respect configured number of threads when doing K2 POW
  profiler/src/main.rs
  src/cipher.rs
  src/prove.rs
  src/verification.rs
Labels: codeball:needs-careful-review

#77 Fix K2 pow performance on many threads
  benches/pow.rs
  src/pow.rs
  tests/generate_and_verify.rs
Labels: milestone/genesis

#78 Release v0.1.14
  Cargo.lock
  Cargo.toml
  ffi/Cargo.toml
  initializer/Cargo.toml
  profiler/Cargo.toml
  scrypt-ocl/Cargo.toml
Labels: codeball:approved
